(()=>{
'use strict';
const DB='love-record-life-apps-v1', STORE='records', VERSION=1;
const $=(s,r=document)=>r.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'RMB '+(Number(n)||0).toFixed(2);
let db, app='food', tab='home', cartKind='food', selectedContactIds=[], activeRoom=null, searchQuery='';
const id=()=>`${Date.now().toString(36)}-${Math.random().toString(36).slice(2,9)}`;
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE)){const s=d.createObjectStore(STORE,{keyPath:'id'});s.createIndex('kind','kind',{unique:false})}};r.onsuccess=()=>{db=r.result;resolve(db)};r.onerror=()=>reject(r.error)})}
function all(kind){return new Promise((resolve,reject)=>{const r=db.transaction(STORE,'readonly').objectStore(STORE).index('kind').getAll(kind);r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)})}
function put(o){return new Promise((resolve,reject)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).put(o);r.onsuccess=()=>resolve(o);r.onerror=()=>reject(r.error)})}
function del(id){return new Promise((resolve,reject)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).delete(id);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)})}
function toast(msg){const t=$('#lr-life-toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2300)}
function people(){try{if(typeof state!=='undefined'&&Array.isArray(state.people))return state.people.filter(p=>p&&p.id&&p.name)}catch{}try{return JSON.parse(localStorage.getItem('love-record-people-recovery-v1')||'[]').filter(p=>p&&p.id&&p.name)}catch{return []}}
function lifeApiConfig(){let saved={};try{saved=JSON.parse(localStorage.getItem('yanyan-love-settings-v5')||'{}')||{}}catch{}let st={};try{if(typeof state!=='undefined')st=state||{}}catch{}const val=(a,b,c)=>String(a||b||c||'').trim();return {base:val(st.apiBase,saved.apiBase,$('#apiBase')?.value).replace(/\/+$/,''),key:val(st.apiKey,saved.apiKey,$('#apiKey')?.value),model:val(st.apiModel,saved.apiModel,$('#apiModel')?.value)}}
async function callLifeAPI(system,user){const cfg=lifeApiConfig();if(!cfg.base||!cfg.key||!cfg.model){toast('请先在 LOVE RECORD 的 API 设置中连接模型');return null}const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),30000);try{const res=await fetch(cfg.base+'/chat/completions',{method:'POST',signal:controller.signal,headers:{'Content-Type':'application/json','Authorization':'Bearer '+cfg.key,'Accept':'application/json'},body:JSON.stringify({model:cfg.model,messages:[{role:'system',content:system},{role:'user',content:user}],stream:false})});const raw=await res.text();if(!res.ok)throw new Error('HTTP '+res.status+' · '+raw.slice(0,180));const data=JSON.parse(raw);const text=data?.choices?.[0]?.message?.content;if(!text)throw new Error('AI 没有返回内容');return Array.isArray(text)?text.map(x=>x.text||'').join('\n'):String(text)}catch(e){toast('AI 请求失败：'+(e.name==='AbortError'?'请求超时':e.message||'未知错误'));return null}finally{clearTimeout(timer)}}
async function runLifeAI(){const isFood=app==='food';const promptEl=$('#life-ai-prompt');const extra=promptEl?.value?.trim()||'';const ps=people().map(p=>({name:p.name,role:p.role||p.title||''}));let catalog=[];if(isFood){const shops=await all('foodShop'),items=await all('foodItem');catalog={shops:shops.map(x=>({name:x.name,category:x.category,fee:x.fee})),items:items.filter(x=>x.active!==false).map(x=>({name:x.name,category:x.category,price:x.price,description:x.description}))}}else{const products=await all('shopProduct');catalog=products.filter(x=>x.active!==false).map(x=>({name:x.name,category:x.category,price:x.price,stock:x.stock,description:x.description}))}const result=await callLifeAPI(isFood?'你是 LOVE RECORD 外卖助手。根据本地菜单、预算和口味给出可执行的推荐。不要声称已真实下单或联系了联系人。':'你是 LOVE RECORD 购物顾问。根据本地商品、预算和送礼对象给出实用建议。不要声称已付款、发货或真实联系了联系人。',`应用：${isFood?'Foodie 外卖':'Orange Market 购物'}\n用户需求：${extra||'请根据当前可选项目给出三种建议'}\n本地目录：${JSON.stringify(catalog)}\nLOVE RECORD 联系人（虚拟角色）：${JSON.stringify(ps)}\n请用简洁中文回答，给出具体商品/菜品、估算金额和理由；如涉及联系人，提供可供用户选择的互动台词/建议，不要伪造真实操作。`);if(result){modal(`<div class=\"life-eyebrow\">AI ${isFood?'FOODIE ASSISTANT':'SHOPPING ASSISTANT'}</div><h2>${isFood?'今天吃什么建议':'购物与送礼建议'}</h2><div class=\"life-ai-result\">${esc(result).replace(/\n/g,'<br>')}</div><div class=\"life-modal-actions\"><button class=\"life-btn primary\" data-life=\"modal-cancel\">知道了</button></div>`);}}

const sampleFoodShops=[
{id:'fs-1',name:'云朵茶餐室',category:'茶餐厅',rating:'4.9',eta:'20–30 分钟',fee:2.5,open:true,description:'轻松的一餐，热腾腾刚刚好。'},
{id:'fs-2',name:'蓝海日式食堂',category:'日式料理',rating:'4.8',eta:'25–35 分钟',fee:3,open:true,description:'寿司、饭类与暖心汤品。'},
{id:'fs-3',name:'小岛甜品屋',category:'饮品甜点',rating:'4.9',eta:'15–25 分钟',fee:1.5,open:true,description:'奶茶、咖啡与今日甜点。'}
];
const sampleFoodItems=[
{id:'fi-1',shopId:'fs-1',name:'奶油鸡扒饭',category:'主食',price:13.9,description:'香煎鸡扒配奶油酱汁',emoji:'🍗',options:'饭量：正常 / 加饭',active:true},
{id:'fi-2',shopId:'fs-1',name:'经典咖喱面',category:'主食',price:11.5,description:'微辣咖喱汤底',emoji:'🍜',options:'辣度：不辣 / 微辣 / 中辣',active:true},
{id:'fi-3',shopId:'fs-1',name:'冰柠檬茶',category:'饮品',price:4.5,description:'清爽柠檬茶',emoji:'🍋',options:'甜度：正常 / 少糖 / 无糖；冰量：正常 / 少冰',active:true},
{id:'fi-4',shopId:'fs-2',name:'三文鱼饭',category:'主食',price:16.9,description:'三文鱼、米饭与时蔬',emoji:'🍣',options:'饭量：正常 / 加饭',active:true},
{id:'fi-5',shopId:'fs-2',name:'照烧鸡肉饭',category:'主食',price:14.9,description:'照烧鸡肉搭配米饭',emoji:'🍱',options:'酱汁：正常 / 另放',active:true},
{id:'fi-6',shopId:'fs-3',name:'紫云奶茶',category:'饮品',price:8.9,description:'奶香与淡淡紫薯香',emoji:'🧋',options:'甜度：正常 / 半糖 / 少糖；冰量：正常 / 少冰 / 去冰',active:true},
{id:'fi-7',shopId:'fs-3',name:'巴斯克芝士蛋糕',category:'甜点',price:10.5,description:'浓郁芝士与焦香表面',emoji:'🍰',options:'份量：一份',active:true}
];
const sampleProducts=[
{id:'sp-1',name:'云朵随行杯',category:'生活好物',price:29.9,stock:18,emoji:'🥤',description:'适合日常通勤的轻便随行杯。',options:'颜色：奶油白 / 蜜桃橙 / 雾蓝',active:true},
{id:'sp-2',name:'柔软居家毯',category:'家居',price:49.9,stock:12,emoji:'🧸',description:'柔软舒适，适合窝在沙发上的夜晚。',options:'颜色：奶油白 / 杏橙',active:true},
{id:'sp-3',name:'手账文具套装',category:'文具',price:19.9,stock:30,emoji:'📒',description:'贴纸、便签和书写笔组合。',options:'款式：橙花 / 小宇宙',active:true},
{id:'sp-4',name:'小花束礼盒',category:'礼物',price:39.9,stock:8,emoji:'💐',description:'适合生日、纪念日和日常惊喜。',options:'颜色：暖橙 / 淡紫 / 白色',active:true},
{id:'sp-5',name:'毛绒小伙伴',category:'玩偶',price:35,stock:15,emoji:'🐻',description:'软乎乎的小熊玩偶。',options:'款式：小熊 / 小兔',active:true},
{id:'sp-6',name:'香氛蜡烛',category:'家居',price:25.9,stock:20,emoji:'🕯️',description:'温柔的香气，让房间放松下来。',options:'香型：白茶 / 柑橘 / 薰衣草',active:true}
];
async function seed(){for(const [kind,list] of [['foodShop',sampleFoodShops],['foodItem',sampleFoodItems],['shopProduct',sampleProducts]]){if(!(await all(kind)).length){for(const x of list)await put({...x,kind})}}}
function injectStyle(){if($('#lr-life-style'))return;const s=document.createElement('style');s.id='lr-life-style';s.textContent=`
#lr-life-app{position:fixed;inset:0;z-index:10020;display:none;background:#f3f8ff;color:#26384c;font-family:inherit;overflow:hidden;--life-accent:#438fce;--life-soft:#e8f4ff;--life-bg:#f3f8ff;--life-ink:#26384c;--life-line:rgba(255,255,255,.9)}
#lr-life-app.orange{background:#fff7eb;--life-accent:#d88735;--life-soft:#fff0d8;--life-bg:#fff7eb;--life-ink:#4b392a}
#lr-life-app.open{display:flex;flex-direction:column}
#lr-life-app *{box-sizing:border-box}
#lr-life-app .life-head{flex-shrink:0;padding:calc(env(safe-area-inset-top) + 13px) 18px 14px;background:rgba(255,255,255,.72);backdrop-filter:blur(24px);border-bottom:1px solid rgba(255,255,255,.8);display:flex;align-items:center;gap:12px}
#lr-life-app .life-back{width:40px;height:40px;border:1px solid #fff;border-radius:50%;background:rgba(255,255,255,.8);font-size:22px;color:var(--life-ink)}
#lr-life-app .life-brand{flex:1;min-width:0}#lr-life-app .life-brand small{display:block;font-size:9px;letter-spacing:3px;opacity:.58}#lr-life-app .life-brand strong{font-size:18px;font-weight:500}
#lr-life-app .life-content{overflow:auto;overscroll-behavior:contain;flex:1;padding:20px 16px calc(96px + env(safe-area-inset-bottom));}
#lr-life-app .life-hero{padding:20px;border:1px solid white;border-radius:26px;background:linear-gradient(135deg,rgba(255,255,255,.86),rgba(255,255,255,.44));box-shadow:0 14px 36px rgba(71,103,143,.08);backdrop-filter:blur(22px);margin-bottom:20px}
#lr-life-app.orange .life-hero{box-shadow:0 14px 36px rgba(166,108,37,.08)}
#lr-life-app .life-eyebrow{font-size:9px;letter-spacing:3px;opacity:.55}#lr-life-app h1{font-size:29px;font-weight:400;line-height:1.25;margin:9px 0}#lr-life-app h2{font-size:20px;font-weight:500;margin:20px 0 12px}#lr-life-app h3{font-size:15px;font-weight:600;margin:0 0 6px}#lr-life-app p{line-height:1.6}
#lr-life-app .life-ai-box{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;align-items:center;margin-top:14px;padding:12px;border:1px solid rgba(255,255,255,.9);border-radius:18px;background:rgba(255,255,255,.48)}#lr-life-app .life-ai-box label,#lr-life-app .life-ai-box small{grid-column:1/-1}#lr-life-app .life-ai-box label{font-size:13px;font-weight:600}#lr-life-app .life-ai-box small{font-size:10px;opacity:.65}#lr-life-app .life-ai-result{white-space:normal;line-height:1.8;padding:12px;border-radius:16px;background:rgba(160,140,190,.08)}
#lr-life-app .life-search{display:flex;gap:8px;margin:14px 0}#lr-life-app input,#lr-life-app select,#lr-life-app textarea{font:inherit;color:inherit;background:rgba(255,255,255,.9);border:1px solid rgba(120,120,140,.15);border-radius:14px;padding:12px;min-width:0;width:100%;outline:none}#lr-life-app textarea{min-height:74px;resize:vertical}
#lr-life-app .life-btn{border:1px solid rgba(255,255,255,.95);border-radius:15px;padding:11px 14px;background:rgba(255,255,255,.8);color:var(--life-ink);font:inherit;white-space:nowrap}#lr-life-app .life-btn.primary{background:var(--life-accent);color:#fff;border-color:transparent}#lr-life-app .life-btn.danger{color:#b34848}#lr-life-app .life-btn.small{padding:7px 10px;font-size:12px}
#lr-life-app .life-row{display:flex;align-items:center;gap:10px}#lr-life-app .life-row>*{min-width:0}#lr-life-app .life-between{justify-content:space-between}#lr-life-app .life-muted{opacity:.63;font-size:12px}#lr-life-app .life-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:11px}
#lr-life-app .life-card{min-width:0;border:1px solid rgba(255,255,255,.95);border-radius:21px;background:rgba(255,255,255,.68);padding:14px;box-shadow:0 8px 22px rgba(60,80,110,.045);backdrop-filter:blur(16px)}
#lr-life-app .life-product-emoji{height:96px;border-radius:16px;background:linear-gradient(145deg,rgba(255,255,255,.92),var(--life-soft));display:grid;place-items:center;font-size:45px;margin-bottom:12px}
#lr-life-app .life-pill{border:1px solid rgba(130,140,160,.16);background:rgba(255,255,255,.65);border-radius:99px;padding:8px 12px;font-size:12px}
#lr-life-app .life-scrollrow{display:flex;gap:8px;overflow:auto;padding:2px 0 8px}#lr-life-app .life-section-title{display:flex;align-items:center;justify-content:space-between;gap:8px}
#lr-life-app .life-item{display:flex;gap:12px;align-items:center;padding:12px 0;border-bottom:1px solid rgba(120,120,140,.13)}#lr-life-app .life-item:last-child{border-bottom:0}
#lr-life-app .life-item-icon{width:52px;height:52px;flex:0 0 52px;border-radius:15px;background:var(--life-soft);display:grid;place-items:center;font-size:25px}
#lr-life-app .life-item-main{flex:1;min-width:0}#lr-life-app .life-item-main p{margin:3px 0;font-size:12px;opacity:.65}
#lr-life-app .life-bottom{position:absolute;bottom:0;left:0;right:0;padding:10px 12px calc(10px + env(safe-area-inset-bottom));background:rgba(255,255,255,.82);border-top:1px solid white;backdrop-filter:blur(25px);display:flex;gap:5px;justify-content:space-around}
#lr-life-app .life-tab{border:0;background:transparent;color:var(--life-ink);opacity:.58;display:flex;flex-direction:column;align-items:center;gap:3px;font:inherit;font-size:10px;padding:6px 5px;flex:1}#lr-life-app .life-tab span{font-size:19px}#lr-life-app .life-tab.active{opacity:1;color:var(--life-accent);font-weight:600}
#lr-life-app .life-empty{text-align:center;padding:30px 15px;opacity:.65;line-height:1.7}#lr-life-app .life-form{display:grid;gap:10px}#lr-life-app .life-field{display:grid;gap:5px;font-size:12px;opacity:.9}
#lr-life-app .life-checks{display:grid;gap:9px}#lr-life-app .life-check{display:flex;gap:9px;align-items:center;padding:10px;border-radius:13px;background:rgba(255,255,255,.7)}#lr-life-app .life-check input{width:auto}
#lr-life-app .life-modal{position:absolute;inset:0;z-index:3;background:rgba(34,32,40,.32);display:none;align-items:flex-end}#lr-life-app .life-modal.show{display:flex}#lr-life-app .life-modal-box{width:100%;max-height:88%;overflow:auto;border-radius:28px 28px 0 0;background:var(--life-bg);padding:20px 17px calc(24px + env(safe-area-inset-bottom));box-shadow:0 -10px 45px rgba(0,0,0,.1)}#lr-life-app .life-modal-actions{display:flex;gap:8px;margin-top:12px}#lr-life-app .life-modal-actions>*{flex:1}
#lr-life-toast{position:absolute;left:50%;bottom:calc(90px + env(safe-area-inset-bottom));transform:translateX(-50%);background:#302d34;color:#fff;border-radius:99px;padding:12px 18px;font-size:13px;max-width:90%;text-align:center;display:none;z-index:9}#lr-life-toast.show{display:block}
@media(min-width:650px){#lr-life-app .life-content{width:min(100%,720px);margin:0 auto}#lr-life-app .life-head{padding-left:max(18px,calc((100% - 720px)/2));padding-right:max(18px,calc((100% - 720px)/2))}#lr-life-app .life-grid{grid-template-columns:repeat(3,minmax(0,1fr))}}
`;document.head.appendChild(s)}
function mount(){if($('#lr-life-app'))return;const el=document.createElement('section');el.id='lr-life-app';el.innerHTML=`<header class="life-head"><button class="life-back" data-life="close" aria-label="返回">‹</button><div class="life-brand"><small id="life-kicker">LOVE RECORD · FOODIE</small><strong id="life-title">今天吃什么？</strong></div><button class="life-btn" data-life="switch" title="切换应用">切换</button></header><div class="life-content" id="life-content"></div><nav class="life-bottom" id="life-bottom"></nav><div class="life-modal" id="life-modal"><div class="life-modal-box" id="life-modal-box"></div></div><div id="lr-life-toast"></div>`;document.body.appendChild(el);
el.addEventListener('click',handleClick);el.addEventListener('submit',handleSubmit);el.addEventListener('change',handleChange);el.addEventListener('input',e=>{if(e.target.matches('[data-life-search]'))searchQuery=e.target.value});
}
async function open(which='food'){try{if(!db)await openDB();await seed();mount();app=which;tab='home';searchQuery='';selectedContactIds=[];$('#lr-life-app').classList.toggle('orange',app==='shop');$('#lr-life-app').classList.add('open');document.body.style.overflow='hidden';render()}catch(e){console.error(e);alert('新应用暂时无法打开，原有资料未被修改。请检查浏览器是否支持 IndexedDB。')}}
function close(){const el=$('#lr-life-app');if(el)el.classList.remove('open');document.body.style.overflow=''}
function switchApp(){app=app==='food'?'shop':'food';tab='home';$('#lr-life-app').classList.toggle('orange',app==='shop');render()}
function title(){return app==='food'?'Foodie · 今天吃什么？':'Orange Market · 想买什么？'}
async function render(){if(!$('#lr-life-app')?.classList.contains('open'))return;$('#life-kicker').textContent=app==='food'?'LOVE RECORD · FOODIE':'LOVE RECORD · ORANGE MARKET';$('#life-title').textContent=title();$('#life-bottom').innerHTML=(app==='food'?[['home','⌂','首页'],['menu','♨','店铺'],['cart','🛒','购物车'],['orders','▤','订单'],['together','♡','一起点餐'],['manage','⚙','管理']]:[['home','⌂','首页'],['products','◇','商城'],['cart','🛍','购物车'],['wishlist','♡','愿望'],['gifts','🎁','礼物'],['orders','▤','订单'],['manage','⚙','管理']]).map(([t,icon,label])=>`<button class="life-tab ${tab===t?'active':''}" data-tab="${t}"><span>${icon}</span>${label}</button>`).join('');
const c=$('#life-content');c.innerHTML='<div class="life-empty">正在整理你的生活小宇宙…</div>';
try{if(app==='food')await renderFood(c);else await renderShop(c)}catch(e){console.error(e);c.innerHTML='<div class="life-empty">这部分暂时无法载入。你的已保存数据没有被主动清除。<br><button class="life-btn" data-life="retry">重新载入</button></div>'}
}
async function renderFood(c){
const shops=await all('foodShop'),items=await all('foodItem'),cart=await all('foodCart'),orders=await all('foodOrder'),rooms=await all('foodRoom');
if(tab==='home'){c.innerHTML=`<section class="life-hero"><div class="life-eyebrow">A LITTLE TASTE OF HOME</div><h1>今天，想吃点什么？</h1><p class="life-muted">挑一顿喜欢的饭，也可以邀请联系人一起决定。</p><div class="life-search"><input data-life-search placeholder="搜索店铺、菜品或口味" value="${esc($('#life-content [data-life-search]')?.value||'')}"><button class="life-btn primary" data-tab="menu">找吃的</button></div><div class="life-row life-between"><span>附近推荐 · 本地模拟菜单</span><span class="life-muted">${shops.length} 家店铺</span></div><div class="life-ai-box"><label for="life-ai-prompt">✦ AI 点餐顾问</label><input id="life-ai-prompt" placeholder="预算、口味、想和谁一起吃……"><button class="life-btn primary" data-life="ai-help">帮我推荐</button><small>使用 LOVE RECORD 已配置的 API；不自动下单。</small></div></section><div class="life-section-title"><h2>精选店铺</h2><button class="life-btn small" data-tab="menu">全部店铺</button></div><div class="life-grid">${shops.slice(0,4).map(s=>`<button class="life-card" data-shop="${esc(s.id)}" style="text-align:left;color:inherit"><div class="life-product-emoji">🍽️</div><h3>${esc(s.name)}</h3><p class="life-muted">${esc(s.category)} · ★ ${esc(s.rating)}<br>${esc(s.eta)} · 配送 ${money(s.fee)}</p></button>`).join('')}</div><h2>今日热门</h2><div class="life-grid">${items.filter(i=>i.active!==false).slice(0,4).map(foodItemCard).join('')}</div><div class="life-card" style="margin-top:14px"><h3>一起点餐</h3><p class="life-muted">创建多人点餐房间，汇总大家想吃的菜。</p><button class="life-btn primary" data-tab="together">发起一起点餐</button></div>`;return}
if(tab==='menu'){const q=searchQuery.trim().toLowerCase();c.innerHTML=`<div class="life-hero"><div class="life-eyebrow">RESTAURANTS & MENU</div><h1>找一家喜欢的店</h1><div class="life-search"><input data-life-search placeholder="搜索店铺或菜品…" value="${esc(q)}"><button class="life-btn primary" data-life="search-food">搜索</button></div><p class="life-muted">所有订单均为应用内模拟订单，不会产生真实付款。</p></div>${shops.map(s=>{const list=items.filter(i=>i.shopId===s.id&&i.active!==false&&(!q||(i.name+' '+s.name+' '+i.category).toLowerCase().includes(q)));return `<section class="life-card" style="margin-bottom:14px"><div class="life-row life-between"><div><h2 style="margin:0 0 5px">${esc(s.name)}</h2><div class="life-muted">${esc(s.category)} · ★ ${esc(s.rating)} · ${esc(s.eta)}</div></div><span class="life-pill">${s.open?'营业中':'休息中'}</span></div><p class="life-muted">${esc(s.description||'')}</p>${list.length?list.map(foodItemRow).join(''):'<p class="life-muted">没有匹配菜品</p>'}</section>`}).join('')}`;return}
if(tab==='cart'){const groups={};for(const x of cart){groups[x.shopId]??=[];groups[x.shopId].push(x)}const entries=Object.entries(groups);const total=cart.reduce((n,x)=>n+x.price*x.qty,0);c.innerHTML=`<div class="life-hero"><div class="life-eyebrow">YOUR CART</div><h1>把喜欢的装进来</h1><p class="life-muted">不同店铺会分别生成订单，金额按当前保存的商品快照计算。</p></div>${entries.length?entries.map(([sid,list])=>`<section class="life-card" style="margin-bottom:12px"><h3>${esc(shops.find(s=>s.id===sid)?.name||'自定义店铺')}</h3>${list.map(x=>`<div class="life-item"><div class="life-item-icon">${esc(x.emoji||'🍽️')}</div><div class="life-item-main"><strong>${esc(x.name)}</strong><p>${esc(x.option||'默认规格')} · ${money(x.price)}</p><div class="life-row"><button class="life-btn small" data-qty="${esc(x.id)}" data-delta="-1">−</button><span>${x.qty}</span><button class="life-btn small" data-qty="${esc(x.id)}" data-delta="1">＋</button><button class="life-btn small danger" data-remove="${esc(x.id)}">移除</button></div></div></div>`).join('')}</section>`).join(''):`<div class="life-empty">购物车还空着。<br>去看看今天想吃什么吧。<br><button class="life-btn primary" data-tab="menu">浏览店铺</button></div>`}<div class="life-card"><div class="life-row life-between"><span>商品小计</span><strong>${money(total)}</strong></div><p class="life-muted">配送费按店铺计算；提交后可填写地址和备注。</p><button class="life-btn primary" style="width:100%" data-life="checkout-food" ${cart.length?'':'disabled'}>确认地址并模拟下单</button></div>`;return}
if(tab==='orders'){c.innerHTML=`<div class="life-hero"><div class="life-eyebrow">ORDER HISTORY</div><h1>每一顿都有记录</h1><p class="life-muted">订单状态可以在本地模拟推进。</p></div>${orders.length?orders.slice().reverse().map(o=>`<div class="life-card" style="margin-bottom:12px"><div class="life-row life-between"><strong>${esc(o.orderNo)}</strong><span class="life-pill">${esc(o.status)}</span></div><p class="life-muted">${esc(o.createdAt)} · ${o.items.length} 件 · ${money(o.total)}</p>${o.items.map(x=>`<div class="life-row life-between"><span>${esc(x.name)} × ${x.qty}</span><span>${money(x.price*x.qty)}</span></div>`).join('')}<hr style="border:0;border-top:1px solid #ddd8;margin:12px 0"><div class="life-row life-between"><strong>${money(o.total)}</strong><div class="life-row">${o.status!=='已送达'&&o.status!=='已取消'?`<button class="life-btn small primary" data-advance-order="${esc(o.id)}">推进状态</button>`:''}<button class="life-btn small" data-reorder="${esc(o.id)}">再来一单</button></div></div></div>`).join(''):'<div class="life-empty">还没有订单。<br>第一顿喜欢的餐，就从这里开始。</div>'}`;return}
if(tab==='together'){c.innerHTML=`<div class="life-hero"><div class="life-eyebrow">TOGETHER TASTES BETTER</div><h1>今晚和谁一起吃？</h1><p class="life-muted">选择多个 LOVE RECORD 联系人，创建本地一起点餐房间。联系人不会收到跨设备实时通知。</p><button class="life-btn primary" data-life="new-room">＋ 创建点餐房间</button></div>${rooms.length?rooms.slice().reverse().map(r=>`<div class="life-card" style="margin-bottom:12px"><div class="life-row life-between"><h3>${esc(r.name)}</h3><span class="life-pill">${esc(r.status||'征集中')}</span></div><p class="life-muted">参与者：${esc((r.peopleNames||[]).join('、')||'你自己')}<br>${esc(r.createdAt)}</p><p>${esc(r.note||'')}</p><button class="life-btn primary" data-room="${esc(r.id)}">打开房间</button> <button class="life-btn small danger" data-delete="${esc(r.id)}" data-kind="foodRoom">删除</button></div>`).join(''):'<div class="life-empty">还没有一起点餐房间。创建后可以从菜单添加候选菜品，再统一汇总。</div>'}`;return}
if(tab==='manage'){c.innerHTML=`<div class="life-hero"><div class="life-eyebrow">LOCAL MANAGEMENT</div><h1>管理你的菜单</h1><p class="life-muted">你可以自行维护店铺和菜品；内置示例数据可以编辑或删除。</p></div><div class="life-grid"><button class="life-card" data-life="add-food-shop"><div class="life-product-emoji">🏪</div><h3>新增店铺</h3><p class="life-muted">店铺名称、分类、配送费</p></button><button class="life-card" data-life="add-food-item"><div class="life-product-emoji">🍱</div><h3>新增菜品</h3><p class="life-muted">菜名、价格、规格与描述</p></button></div><h2>店铺管理</h2>${shops.map(s=>`<div class="life-item"><div class="life-item-icon">🏪</div><div class="life-item-main"><strong>${esc(s.name)}</strong><p>${esc(s.category)} · 配送 ${money(s.fee)}</p><button class="life-btn small" data-edit-shop="${esc(s.id)}">编辑</button> <button class="life-btn small danger" data-delete="${esc(s.id)}" data-kind="foodShop">删除</button></div></div>`).join('')}<h2>菜品管理</h2>${items.map(i=>`<div class="life-item"><div class="life-item-icon">${esc(i.emoji||'🍽️')}</div><div class="life-item-main"><strong>${esc(i.name)}</strong><p>${money(i.price)} · ${esc(shops.find(s=>s.id===i.shopId)?.name||'')}</p><button class="life-btn small" data-edit-food="${esc(i.id)}">编辑</button> <button class="life-btn small danger" data-delete="${esc(i.id)}" data-kind="foodItem">删除</button></div></div>`).join('')}`;return}
}
function foodItemCard(i){return `<div class="life-card"><div class="life-product-emoji">${esc(i.emoji||'🍽️')}</div><h3>${esc(i.name)}</h3><p class="life-muted">${esc(i.description||'')}</p><div class="life-row life-between"><strong>${money(i.price)}</strong><button class="life-btn primary small" data-add-food="${esc(i.id)}">＋ 加入</button></div></div>`}
function foodItemRow(i){return `<div class="life-item"><div class="life-item-icon">${esc(i.emoji||'🍽️')}</div><div class="life-item-main"><strong>${esc(i.name)}</strong><p>${esc(i.description||'')}</p><p>${money(i.price)} · ${esc(i.options||'默认规格')}</p><div class="life-row"><button class="life-btn small primary" data-add-food="${esc(i.id)}">＋ 加入购物车</button><button class="life-btn small" data-food-detail="${esc(i.id)}">选择规格</button></div></div></div>`}
async function renderShop(c){
const products=await all('shopProduct'),cart=await all('shopCart'),orders=await all('shopOrder'),wishes=await all('wishlist'),gifts=await all('giftPlan');
if(tab==='home'||tab==='products'){const q=searchQuery.trim().toLowerCase();const list=products.filter(p=>p.active!==false&&(!q||(p.name+' '+p.category+' '+p.description).toLowerCase().includes(q)));c.innerHTML=`<section class="life-hero"><div class="life-eyebrow">LITTLE THINGS, BIG JOY</div><h1>${tab==='home'?'给日常添一点喜欢':'逛逛小商城'}</h1><p class="life-muted">本地自建商品商城。可以逛商品、管理库存、记录愿望，也可以为联系人准备礼物。</p><div class="life-search"><input data-life-search placeholder="搜索商品、分类…" value="${esc(q)}"><button class="life-btn primary" data-tab="products">搜索</button></div><div class="life-scrollrow"><button class="life-pill" data-category="全部">全部</button>${[...new Set(products.map(p=>p.category))].map(x=>`<button class="life-pill" data-category="${esc(x)}">${esc(x)}</button>`).join('')}</div>${tab==='home'?`<div class="life-ai-box"><label for="life-ai-prompt">✦ AI 购物顾问</label><input id="life-ai-prompt" placeholder="预算、用途、送给哪位联系人……"><button class="life-btn primary" data-life="ai-help">帮我挑选</button><small>使用 LOVE RECORD 已配置的 API；不自动购买。</small></div>`:''}</section><div class="life-section-title"><h2>${tab==='home'?'为你精选':'全部商品'}</h2><span class="life-muted">${list.length} 件商品</span></div><div class="life-grid">${list.map(shopProductCard).join('')||'<div class="life-empty">没有找到商品。</div>'}</div>${tab==='home'?`<div class="life-card" style="margin-top:16px"><h3>把喜欢的东西记下来</h3><p class="life-muted">不一定现在就买。先放进愿望清单，慢慢决定也可以。</p><button class="life-btn primary" data-tab="wishlist">打开愿望清单</button></div>`:''}`;return}
if(tab==='cart'){const total=cart.reduce((n,x)=>n+x.price*x.qty,0);c.innerHTML=`<div class="life-hero"><div class="life-eyebrow">SHOPPING BAG</div><h1>想要的，都在这里</h1><p class="life-muted">这是模拟商城，不会进行真实付款或发货。</p></div>${cart.length?cart.map(x=>`<div class="life-card" style="margin-bottom:10px"><div class="life-item"><div class="life-item-icon">${esc(x.emoji||'🎁')}</div><div class="life-item-main"><strong>${esc(x.name)}</strong><p>${esc(x.option||'默认款式')} · ${money(x.price)}</p><div class="life-row"><button class="life-btn small" data-shop-qty="${esc(x.id)}" data-delta="-1">−</button><span>${x.qty}</span><button class="life-btn small" data-shop-qty="${esc(x.id)}" data-delta="1">＋</button><button class="life-btn small danger" data-remove="${esc(x.id)}">移除</button></div></div></div></div>`).join(''):'<div class="life-empty">购物袋还是空的。<br><button class="life-btn primary" data-tab="products">去逛商城</button></div>'}<div class="life-card"><div class="life-row life-between"><span>商品小计</span><strong>${money(total)}</strong></div><p class="life-muted">运费为本地模拟值 RMB 5.00；结算前可填写收货地址。</p><button class="life-btn primary" style="width:100%" data-life="checkout-shop" ${cart.length?'':'disabled'}>确认信息并创建订单</button></div>`;return}
if(tab==='orders'){c.innerHTML=`<div class="life-hero"><div class="life-eyebrow">YOUR PURCHASES</div><h1>购买记录</h1><p class="life-muted">记录模拟订单、状态与历史价格。</p></div>${orders.length?orders.slice().reverse().map(o=>`<div class="life-card" style="margin-bottom:12px"><div class="life-row life-between"><strong>${esc(o.orderNo)}</strong><span class="life-pill">${esc(o.status)}</span></div><p class="life-muted">${esc(o.createdAt)} · ${o.items.length} 件商品</p>${o.items.map(x=>`<div class="life-row life-between"><span>${esc(x.name)} × ${x.qty}</span><span>${money(x.price*x.qty)}</span></div>`).join('')}<hr style="border:0;border-top:1px solid #ddd8;margin:12px 0"><div class="life-row life-between"><strong>${money(o.total)}</strong><div class="life-row">${o.status!=='已完成'&&o.status!=='已取消'?`<button class="life-btn small primary" data-advance-shop-order="${esc(o.id)}">推进状态</button>`:''}<button class="life-btn small" data-reorder-shop="${esc(o.id)}">再买一次</button></div></div></div>`).join(''):'<div class="life-empty">还没有购买记录。</div>'}`;return}
if(tab==='wishlist'){c.innerHTML=`<div class="life-hero"><div class="life-eyebrow">SOMEDAY LIST</div><h1>想要的，不急着买</h1><p class="life-muted">创建多个清单，记录预算、优先级、目标日期和自定义想买的东西。</p><button class="life-btn primary" data-life="new-wishlist">＋ 新建愿望清单</button></div>${wishes.length?wishes.slice().reverse().map(w=>`<div class="life-card" style="margin-bottom:12px"><div class="life-row life-between"><h3>${esc(w.name)}</h3><span class="life-pill">${esc(w.priority||'普通')}</span></div><p class="life-muted">预算 ${money(w.budget)} · 目标日期 ${esc(w.date||'未设定')}</p><p>${esc(w.note||'')}</p>${(w.items||[]).map(x=>`<div class="life-row life-between"><span>${esc(x.name)}</span><span>${money(x.price)}</span></div>`).join('')}<div style="margin-top:12px"><button class="life-btn small" data-edit-wishlist="${esc(w.id)}">编辑</button> <button class="life-btn small" data-wish-add="${esc(w.id)}">添加自定义商品</button> <button class="life-btn small danger" data-delete="${esc(w.id)}" data-kind="wishlist">删除</button></div></div>`).join(''):'<div class="life-empty">还没有愿望清单。可以先把想买的东西放在这里。</div>'}`;return}
if(tab==='gifts'){c.innerHTML=`<div class="life-hero"><div class="life-eyebrow">A GIFT FOR SOMEONE</div><h1>给重要的人准备惊喜</h1><p class="life-muted">关联 LOVE RECORD 联系人，保存礼物候选、预算、日期和准备进度。</p><button class="life-btn primary" data-life="new-gift">＋ 创建礼物计划</button></div>${gifts.length?gifts.slice().reverse().map(g=>`<div class="life-card" style="margin-bottom:12px"><div class="life-row life-between"><h3>${esc(g.title)}</h3><span class="life-pill">${esc(g.status)}</span></div><p class="life-muted">送给：${esc(g.personName||'待选择')} · 预算 ${money(g.budget)}<br>日期：${esc(g.date||'未设置')}</p><p>${esc(g.note||'')}</p>${(g.candidates||[]).map(x=>`<div class="life-row life-between"><span>${esc(x.name)}</span><span>${money(x.price)}</span></div>`).join('')}<div style="margin-top:12px"><button class="life-btn small" data-edit-gift="${esc(g.id)}">编辑计划</button> <button class="life-btn small" data-delete="${esc(g.id)}" data-kind="giftPlan">删除</button></div></div>`).join(''):'<div class="life-empty">创建一份礼物计划，可以慢慢比较候选商品。</div>'}`;return}
if(tab==='manage'){c.innerHTML=`<div class="life-hero"><div class="life-eyebrow">YOUR OWN SHOP</div><h1>商城管理</h1><p class="life-muted">自行新增商品、调整价格和库存。数据保存在本设备的专用数据库。</p><button class="life-btn primary" data-life="add-product">＋ 新增商品</button> <button class="life-btn" data-life="export">导出数据备份</button></div>${products.map(p=>`<div class="life-item"><div class="life-item-icon">${esc(p.emoji||'🎁')}</div><div class="life-item-main"><strong>${esc(p.name)}</strong><p>${money(p.price)} · 库存 ${Number(p.stock)||0} · ${esc(p.category)}</p><button class="life-btn small" data-edit-product="${esc(p.id)}">编辑</button> <button class="life-btn small danger" data-delete="${esc(p.id)}" data-kind="shopProduct">删除</button></div></div>`).join('')}`;return}
}
function shopProductCard(p){return `<div class="life-card"><div class="life-product-emoji">${esc(p.emoji||'🎁')}</div><div class="life-muted">${esc(p.category)}</div><h3>${esc(p.name)}</h3><p class="life-muted">${esc(p.description||'')}</p><div class="life-row life-between"><strong>${money(p.price)}</strong><button class="life-btn primary small" data-add-product="${esc(p.id)}">＋ 加入</button></div><div class="life-row life-between" style="margin-top:7px"><button class="life-btn small" data-wishlist-product="${esc(p.id)}">♡ 愿望</button><span class="life-muted">库存 ${Number(p.stock)||0}</span></div></div>`}
function modal(content){$('#life-modal-box').innerHTML=content;$('#life-modal').classList.add('show')}
function closeModal(){$('#life-modal').classList.remove('show')}
function field(label,name,value='',placeholder='',type='text'){return `<label class="life-field">${label}<input name="${name}" type="${type}" value="${esc(value)}" placeholder="${esc(placeholder)}"></label>`}
function selectField(label,name,options,value){return `<label class="life-field">${label}<select name="${name}">${options.map(o=>`<option value="${esc(o.value)}" ${o.value===value?'selected':''}>${esc(o.label)}</option>`).join('')}</select></label>`}
function formModal(title,kind,obj={},fields=''){modal(`<div class="life-eyebrow">EDIT YOUR WORLD</div><h2 style="margin-top:7px">${title}</h2><form data-form="${kind}" data-id="${esc(obj.id||'')}" data-item-id="${esc(obj.itemId||'')}" data-product-id="${esc(obj.productId||'')}"><div class="life-form">${fields}</div><div class="life-modal-actions"><button type="button" class="life-btn" data-life="modal-cancel">取消</button><button class="life-btn primary" type="submit">保存</button></div></form>`)}
function shopOptions(){return all('foodShop')}
async function handleClick(e){const b=e.target.closest('button');if(!b)return;
if(b.dataset.life==='close'){close();return}if(b.dataset.life==='switch'){switchApp();return}if(b.dataset.life==='retry'){render();return}if(b.dataset.life==='search-food'){render();return}if(b.dataset.life==='modal-cancel'){closeModal();return}
if(b.dataset.tab){tab=b.dataset.tab;render();return}
if(b.dataset.category){searchQuery=b.dataset.category==='全部'?'':b.dataset.category;tab='products';render();return}
if(b.dataset.shop){tab='menu';render();return}
if(b.dataset.addFood){const item=(await all('foodItem')).find(x=>x.id===b.dataset.addFood);if(item){await addFoodToCart(item,'默认规格')}return}
if(b.dataset.foodDetail){const item=(await all('foodItem')).find(x=>x.id===b.dataset.foodDetail);if(item){const opts=(item.options||'默认规格').split(/[；;]/).map(x=>x.trim()).filter(Boolean);formModal('选择菜品规格','food-option',{itemId:item.id},`${selectField('规格','option',opts.map(o=>({value:o,label:o})),opts[0]||'默认规格')}<div class="life-muted">${esc(item.description||'')}</div>`)}return}
if(b.dataset.addProduct){const p=(await all('shopProduct')).find(x=>x.id===b.dataset.addProduct);if(p){const opts=(p.options||'默认款式').split(/[；;]/).map(x=>x.trim()).filter(Boolean);formModal('选择商品款式','product-option',{productId:p.id},`${selectField('款式 / 规格','option',opts.map(o=>({value:o,label:o})),opts[0]||'默认款式')}<div class="life-muted">库存 ${Number(p.stock)||0} · ${money(p.price)}</div>`)}return}
if(b.dataset.wishlistProduct){const p=(await all('shopProduct')).find(x=>x.id===b.dataset.wishlistProduct);if(p){const wishes=await all('wishlist');if(wishes.length){modal(`<h2>加入愿望清单</h2><div class="life-form">${selectField('选择清单','wishId',wishes.map(w=>({value:w.id,label:w.name})),wishes[0].id)}</div><div class="life-modal-actions"><button class="life-btn" data-life="modal-cancel">取消</button><button class="life-btn primary" data-life="add-wish-existing" data-product="${esc(p.id)}">加入</button></div>`)}else{await put({id:id(),kind:'wishlist',name:'我的愿望清单',budget:0,priority:'普通',date:'',note:'',items:[{name:p.name,price:p.price,productId:p.id}]});toast('已创建愿望清单并加入商品');render()}}return}
if(b.dataset.qty){const x=(await all('foodCart')).find(x=>x.id===b.dataset.qty);if(x){if(+b.dataset.delta<0&&x.qty<=1)await del(x.id);else await put({...x,qty:x.qty+(+b.dataset.delta)});render()}return}
if(b.dataset.shopQty){const x=(await all('shopCart')).find(x=>x.id===b.dataset.shopQty);if(x){if(+b.dataset.delta<0&&x.qty<=1)await del(x.id);else await put({...x,qty:x.qty+(+b.dataset.delta)});render()}return}
if(b.dataset.remove){await del(b.dataset.remove);toast('已从购物车移除');render();return}
if(b.dataset.life==='checkout-food'){await checkout('food');return}if(b.dataset.life==='checkout-shop'){await checkout('shop');return}if(b.dataset.life==='ai-help'){b.disabled=true;b.textContent='正在请求 AI…';try{await runLifeAI()}finally{b.disabled=false;b.textContent=app==='food'?'帮我推荐':'帮我挑选'}return}
if(b.dataset.life==='new-room'){const ps=people();selectedContactIds=[];formModal('创建一起点餐房间','new-room',{},`${field('房间名称','name','今晚吃什么','例如：周五晚餐')}${field('补充说明','note','','口味、预算或备注')}${ps.length?`<div class="life-field">邀请联系人（可多选）<div class="life-checks">${ps.map(p=>`<label class="life-check"><input type="checkbox" name="personIds" value="${esc(p.id)}"> ${esc(p.name)} <span class="life-muted">${esc(p.role||'')}</span></label>`).join('')}</div></div>`:'<p class="life-muted">还没有可选联系人。你可以先在 LOVE RECORD 的联系人里创建人物。</p>'}`);return}
if(b.dataset.room){const r=(await all('foodRoom')).find(x=>x.id===b.dataset.room);if(r){activeRoom=r.id;const items=await all('foodItem'),ps=people().filter(p=>(r.peopleIds||[]).includes(String(p.id)));r.votes=r.votes||{};r.comments=r.comments||[];modal(`<div class="life-eyebrow">GROUP ORDER</div><h2>${esc(r.name)}</h2><p class="life-muted">参与者：${esc((r.peopleNames||[]).join('、')||'你自己')}</p><h3>添加候选菜品</h3><div class="life-form">${selectField('菜品','foodItem',items.map(x=>({value:x.id,label:`${x.name} · ${money(x.price)}`})),items[0]?.id||'')}</div><div class="life-modal-actions"><button class="life-btn" data-life="modal-cancel">关闭</button><button class="life-btn primary" data-life="room-add-item">加入候选</button></div><div style="margin-top:16px"><h3>候选菜单 · 投票</h3>${(r.candidates||[]).map((x,i)=>`<div class="life-card" style="margin:8px 0"><div class="life-row life-between"><strong>${esc(x.name)} × ${x.qty}</strong><span>${money(x.price*x.qty)}</span></div><p class="life-muted">投票：${esc(((r.votes[i]||[]).map(pid=>ps.find(p=>String(p.id)===String(pid))?.name||'联系人')).join('、')||'暂无')} · ${(r.votes[i]||[]).length} 票</p>${ps.length?`<button class="life-btn small" data-life="room-vote" data-id="${esc(r.id)}" data-index="${i}">为这道菜投票</button>`:''}</div>`).join('')||'<p class="life-muted">还没有候选菜品</p>'}<p><strong>候选合计 ${money((r.candidates||[]).reduce((n,x)=>n+x.price*x.qty,0))}</strong></p><button class="life-btn primary" data-life="room-order" data-id="${esc(r.id)}">汇总到购物车</button><h3 style="margin-top:18px">讨论一下</h3>${ps.length?selectField('以谁的身份记录','commentPerson',ps.map(p=>({value:String(p.id),label:p.name})),String(ps[0].id)):'<p class="life-muted">没有可选联系人时，也可以由你自己讨论。</p>'}<textarea id="life-room-comment" placeholder="写下口味、预算或想法……"></textarea><button class="life-btn" style="margin-top:8px" data-life="room-comment" data-id="${esc(r.id)}">添加评论</button>${r.comments.length?`<div style="margin-top:12px">${r.comments.map(c=>`<div class="life-card" style="margin-top:8px"><strong>${esc(c.author)}</strong><p>${esc(c.text)}</p><span class="life-muted">${esc(c.date)}</span></div>`).join('')}</div>`:''}</div>`)}return}
if(b.dataset.life==='room-vote'){const room=(await all('foodRoom')).find(x=>x.id===b.dataset.id);if(room){const ps=people().filter(p=>(room.peopleIds||[]).includes(String(p.id)));if(!ps.length){toast('这个房间没有可投票的联系人');return}modal(`<h2>记录投票</h2><p class="life-muted">这是本地模拟互动，不会向联系人发送真实通知。</p>${selectField('选择联系人','votePerson',ps.map(p=>({value:String(p.id),label:p.name})),String(ps[0].id))}<div class="life-modal-actions"><button class="life-btn" data-life="modal-cancel">取消</button><button class="life-btn primary" data-life="confirm-room-vote" data-id="${esc(room.id)}" data-index="${esc(b.dataset.index)}">确认投票</button></div>`)}return}
if(b.dataset.life==='confirm-room-vote'){const room=(await all('foodRoom')).find(x=>x.id===b.dataset.id),pid=$('#life-modal select[name="votePerson"]')?.value;if(room&&pid){room.votes=room.votes||{};const idx=String(b.dataset.index);room.votes[idx]=room.votes[idx]||[];room.votes[idx]=room.votes[idx].filter(x=>String(x)!==String(pid));room.votes[idx].push(String(pid));await put(room);closeModal();await render();const rb=$(`[data-room="${room.id}"]`);if(rb)rb.click();toast('投票已记录')}return}
if(b.dataset.life==='room-comment'){const room=(await all('foodRoom')).find(x=>x.id===b.dataset.id),txt=$('#life-room-comment')?.value?.trim(),pid=$('#life-modal select[name="commentPerson"]')?.value,person=people().find(p=>String(p.id)===String(pid));if(room&&txt){room.comments=room.comments||[];room.comments.push({author:person?.name||'我',text:txt,date:new Date().toLocaleString()});await put(room);closeModal();await render();const rb=$(`[data-room="${room.id}"]`);if(rb)rb.click();toast('评论已保存')}else toast('先写下一点想法吧');return}
if(b.dataset.life==='room-add-item'){const room=(await all('foodRoom')).find(x=>x.id===activeRoom);const iid=$('#life-modal select[name="foodItem"]')?.value;const item=(await all('foodItem')).find(x=>x.id===iid);if(room&&item){room.candidates=room.candidates||[];room.candidates.push({name:item.name,price:item.price,qty:1,emoji:item.emoji,shopId:item.shopId,option:'一起点餐候选'});await put(room);toast('已加入候选菜品');await render();const btn=$(`[data-room="${room.id}"]`);if(btn)btn.click()}return}
if(b.dataset.life==='room-order'){const room=(await all('foodRoom')).find(x=>x.id===b.dataset.id);if(room){for(const x of room.candidates||[]){const cart=await all('foodCart');const found=cart.find(c=>c.name===x.name&&c.shopId===x.shopId&&c.option===x.option);if(found)await put({...found,qty:found.qty+x.qty});else await put({id:id(),kind:'foodCart',...x,id:id()})}closeModal();tab='cart';render();toast('候选菜单已汇总到购物车')}return}
if(b.dataset.life==='add-food-shop'){const empty={};formModal('新增店铺','food-shop',empty,`${field('店铺名称','name','','例如：小岛餐厅')}${field('分类','category','家常菜')}${field('评分','rating','4.8','4.8')}${field('预计送达','eta','20–30 分钟')}${field('配送费 RM','fee','2.50','0','number')}${field('介绍','description','','店铺介绍')}`);return}
if(b.dataset.life==='add-food-item'){const shops=await all('foodShop');formModal('新增菜品','food-item',{},`${field('菜品名称','name','','例如：招牌鸡饭')}${selectField('所属店铺','shopId',shops.map(x=>({value:x.id,label:x.name})),shops[0]?.id||'')}${field('价格 RM','price','10.00','','number')}${field('分类','category','主食')}${field('表情图标','emoji','🍱')}${field('规格选项','options','辣度：不辣 / 微辣')}${field('介绍','description','','菜品介绍')}`);return}
if(b.dataset.editShop){const x=(await all('foodShop')).find(v=>v.id===b.dataset.editShop);if(x)formModal('编辑店铺','food-shop',x,`${field('店铺名称','name',x.name)}${field('分类','category',x.category)}${field('评分','rating',x.rating)}${field('预计送达','eta',x.eta)}${field('配送费 RM','fee',x.fee,'','number')}${field('介绍','description',x.description||'')}`);return}
if(b.dataset.editFood){const x=(await all('foodItem')).find(v=>v.id===b.dataset.editFood),shops=await all('foodShop');if(x)formModal('编辑菜品','food-item',x,`${field('菜品名称','name',x.name)}${selectField('所属店铺','shopId',shops.map(v=>({value:v.id,label:v.name})),x.shopId)}${field('价格 RM','price',x.price,'','number')}${field('分类','category',x.category)}${field('表情图标','emoji',x.emoji||'🍽️')}${field('规格选项','options',x.options||'默认规格')}${field('介绍','description',x.description||'')}`);return}
if(b.dataset.life==='add-product'){formModal('新增商品','shop-product',{},`${field('商品名称','name','','商品名称')}${field('分类','category','生活好物')}${field('价格 RM','price','10.00','','number')}${field('库存','stock','10','','number')}${field('表情图标','emoji','🎁')}${field('规格选项','options','颜色：奶油白 / 蜜桃橙')}${field('介绍','description','','商品介绍')}`);return}
if(b.dataset.editProduct){const x=(await all('shopProduct')).find(v=>v.id===b.dataset.editProduct);if(x)formModal('编辑商品','shop-product',x,`${field('商品名称','name',x.name)}${field('分类','category',x.category)}${field('价格 RM','price',x.price,'','number')}${field('库存','stock',x.stock,'','number')}${field('表情图标','emoji',x.emoji||'🎁')}${field('规格选项','options',x.options||'默认款式')}${field('介绍','description',x.description||'')}`);return}
if(b.dataset.life==='new-wishlist'){formModal('新建愿望清单','wishlist',{},`${field('清单名称','name','我的愿望清单')}${field('预算 RM','budget','0','','number')}${selectField('优先级','priority',[{value:'低',label:'低'},{value:'普通',label:'普通'},{value:'高',label:'高'}],'普通')}${field('目标日期','date','','','date')}${field('备注','note','','')}`);return}
if(b.dataset.wishAdd){const w=(await all('wishlist')).find(x=>x.id===b.dataset.wishAdd);if(w)formModal('添加自定义愿望','wish-item',w,`${field('商品名称','itemName','','想买什么？')}${field('价格 RM','itemPrice','0','','number')}`);return}
if(b.dataset.editWishlist){const w=(await all('wishlist')).find(x=>x.id===b.dataset.editWishlist);if(w)formModal('编辑愿望清单','wishlist',w,`${field('清单名称','name',w.name)}${field('预算 RM','budget',w.budget||0,'','number')}${selectField('优先级','priority',[{value:'低',label:'低'},{value:'普通',label:'普通'},{value:'高',label:'高'}],w.priority||'普通')}${field('目标日期','date',w.date||'','','date')}${field('备注','note',w.note||'')}`);return}
if(b.dataset.life==='new-gift'){const ps=people(),products=await all('shopProduct');formModal('创建礼物计划','gift-plan',{},`${field('计划名称','title','生日惊喜')}${selectField('送给谁','personId',ps.map(p=>({value:String(p.id),label:p.name})),ps[0]?String(ps[0].id):'')}${field('预算 RM','budget','50','','number')}${field('送礼日期','date','','','date')}${field('候选商品（可填名称）','candidateName',products[0]?.name||'')}${field('候选价格 RM','candidatePrice',products[0]?.price||0,'','number')}${field('备注','note','','')}`);return}
if(b.dataset.editGift){const g=(await all('giftPlan')).find(x=>x.id===b.dataset.editGift),ps=people();if(g)formModal('编辑礼物计划','gift-plan',g,`${field('计划名称','title',g.title)}${selectField('送给谁','personId',ps.map(p=>({value:String(p.id),label:p.name})),String(g.personId||''))}${field('预算 RM','budget',g.budget||0,'','number')}${field('送礼日期','date',g.date||'','','date')}${field('候选商品（可填名称）','candidateName',g.candidates?.[0]?.name||'')}${field('候选价格 RM', 'candidatePrice',g.candidates?.[0]?.price||0,'','number')}${field('状态','status',g.status||'准备中')}${field('备注','note',g.note||'')}`);return}
if(b.dataset.life==='add-wish-existing'){const pid=b.dataset.product,wid=$('#life-modal select[name="wishId"]')?.value,p=(await all('shopProduct')).find(x=>x.id===pid),w=(await all('wishlist')).find(x=>x.id===wid);if(p&&w){w.items=w.items||[];w.items.push({name:p.name,price:p.price,productId:p.id});await put(w);closeModal();toast('已加入愿望清单');render()}return}
if(b.dataset.advanceOrder||b.dataset.advanceShopOrder){const kind=b.dataset.advanceOrder?'foodOrder':'shopOrder',oid=b.dataset.advanceOrder||b.dataset.advanceShopOrder,o=(await all(kind)).find(x=>x.id===oid);if(o){const steps=kind==='foodOrder'?['商家已接单','备餐中','配送中','已送达']:['订单已确认','准备中','配送中','已完成'];o.status=steps[Math.min(steps.indexOf(o.status)+1,steps.length-1)]||steps[0];await put(o);toast('订单状态已更新');render()}return}
if(b.dataset.reorder||b.dataset.reorderShop){const kind=b.dataset.reorder?'foodOrder':'shopOrder',oid=b.dataset.reorder||b.dataset.reorderShop,o=(await all(kind)).find(x=>x.id===oid);if(o){const cartKind=kind==='foodOrder'?'foodCart':'shopCart';for(const x of o.items){const {id:oldid,...copy}=x;await put({...copy,id:id(),kind:cartKind,qty:x.qty})}tab='cart';render();toast('已将商品加入购物车')}return}
if(b.dataset.delete){const kind=b.dataset.kind;if(kind&&confirm('确定删除这条记录吗？')){await del(b.dataset.delete);toast('已删除');render()}return}
if(b.dataset.life==='export'){await exportData();return}
}
async function addFoodToCart(item,option){const shop=(await all('foodShop')).find(s=>s.id===item.shopId);if(!shop?.open){toast('这家店目前休息中');return}const cart=await all('foodCart'),found=cart.find(x=>x.itemId===item.id&&x.option===option);if(found)await put({...found,qty:found.qty+1});else await put({id:id(),kind:'foodCart',itemId:item.id,shopId:item.shopId,name:item.name,price:Number(item.price)||0,qty:1,emoji:item.emoji||'🍽️',option,description:item.description||''});toast('已加入购物车');}
async function checkout(which){const isFood=which==='food',kind=isFood?'foodCart':'shopCart',cart=await all(kind);if(!cart.length)return;const shops=isFood?await all('foodShop'):[],saved=await all('savedAddress');const subtotal=cart.reduce((n,x)=>n+x.price*x.qty,0),total=subtotal+(isFood?[...new Set(cart.map(x=>x.shopId))].reduce((n,sid)=>n+(shops.find(s=>s.id===sid)?.fee||0),0):5);const ps=people();formModal(isFood?'确认外卖订单':'确认购物订单',isFood?'checkout-food':'checkout-shop',{},`${field('收货人','recipient','','姓名')}${field('联系电话','phone','','电话号码')}${saved.length?selectField('使用已保存地址（可选）','savedAddress',[{value:'',label:'手动填写新地址'},...saved.map(a=>({value:a.id,label:a.label+' · '+a.address}))],''):''}${field('配送 / 收货地址','address','','完整地址')}${saved.length?'<p class="life-muted">选择已保存地址后，仍可在上方修改本次订单地址。</p>':''}<label class="life-check"><input type="checkbox" name="saveAddress" value="yes"> 将本次地址保存到地址簿</label>${field('备注','note','','可选备注')}${isFood?field('餐具偏好','cutlery','需要餐具') : field('模拟配送方式','delivery','标准配送')}${ps.length?selectField('关联联系人（可选）','contactId',[{value:'',label:'不关联联系人'},...ps.map(p=>({value:String(p.id),label:p.name}))],''):''}<div class="life-card"><div class="life-row life-between"><span>商品金额</span><strong>${money(subtotal)}</strong></div>${isFood?`<div class="life-row life-between"><span>配送费</span><strong>${money([...new Set(cart.map(x=>x.shopId))].reduce((n,sid)=>n+(shops.find(s=>s.id===sid)?.fee||0),0))}</strong></div>`:'<div class="life-row life-between"><span>模拟运费</span><strong>RMB 5.00</strong></div>'}<div class="life-row life-between"><strong>订单金额</strong><strong>${money(total)}</strong></div><p class="life-muted">模拟订单，不会扣款。</p></div>`);const f=$('#life-modal form');f.dataset.checkout=which;}
async function handleSubmit(e){const f=e.target.closest('form[data-form]');if(!f)return;e.preventDefault();const fd=new FormData(f),v=Object.fromEntries(fd.entries()),kind=f.dataset.form,oid=f.dataset.id;try{
if(kind==='food-option'){const item=(await all('foodItem')).find(x=>x.id===f.dataset.itemId)||null;const opt=v.option||'默认规格';const actual=item||{id:$('#life-modal').dataset.itemId};if(item)await addFoodToCart(item,opt);closeModal();render();return}
if(kind==='product-option'){const p=(await all('shopProduct')).find(x=>x.id===f.dataset.productId);if(p){if(Number(p.stock)<=0){toast('该商品暂时缺货');return}const cart=await all('shopCart'),found=cart.find(x=>x.productId===p.id&&x.option===v.option);if(found)await put({...found,qty:found.qty+1});else await put({id:id(),kind:'shopCart',productId:p.id,name:p.name,price:Number(p.price)||0,qty:1,emoji:p.emoji||'🎁',option:v.option||'默认款式'});toast('已加入购物车')}closeModal();render();return}
if(f.dataset.checkout){const which=f.dataset.checkout,isFood=which==='food',cartKind=isFood?'foodCart':'shopCart',orderKind=isFood?'foodOrder':'shopOrder',cart=await all(cartKind),shops=isFood?await all('foodShop'):[];if(v.savedAddress){const saved=(await all('savedAddress')).find(a=>a.id===v.savedAddress);if(saved&&!v.address?.trim())v.address=saved.address}if(!v.address?.trim()){toast('请先填写收货地址');return}if(v.saveAddress==='yes'&&!(await all('savedAddress')).some(a=>a.address===v.address)){await put({id:id(),kind:'savedAddress',label:v.recipient||'常用地址',address:v.address,phone:v.phone||''})}const groups=isFood?[...new Set(cart.map(x=>x.shopId))].map(shopId=>({shopId,items:cart.filter(x=>x.shopId===shopId)})):[{shopId:'',items:cart}];for(let gi=0;gi<groups.length;gi++){const group=groups[gi],items=group.items.map(x=>({name:x.name,price:x.price,qty:x.qty,option:x.option||'',emoji:x.emoji||'',shopId:x.shopId||'',productId:x.productId||'',itemId:x.itemId||''})),subtotal=items.reduce((n,x)=>n+x.price*x.qty,0),fees=isFood?(shops.find(s=>s.id===group.shopId)?.fee||0):5;const order={id:id(),kind:orderKind,orderNo:(isFood?'FD':'MK')+'-'+Date.now().toString().slice(-6)+'-'+(gi+1),status:isFood?'商家已接单':'订单已确认',createdAt:new Date().toLocaleString(),items,total:subtotal+fees,fees,recipient:v.recipient||'',phone:v.phone||'',address:v.address,note:v.note||'',delivery:v.delivery||'',cutlery:v.cutlery||'',contactId:v.contactId||'',contactName:people().find(p=>String(p.id)===String(v.contactId))?.name||'',mode:'local-simulation'};await put(order)}for(const x of cart)await del(x.id);if(!isFood){for(const x of cart){const p=(await all('shopProduct')).find(p=>p.id===x.productId);if(p){p.stock=Math.max(0,(Number(p.stock)||0)-x.qty);await put(p)}}}closeModal();tab='orders';render();toast(isFood&&groups.length>1?`已保存 ${groups.length} 个店铺订单！`:'订单已保存！这是本地模拟订单');return}
const data={id:oid||id(),kind:kind==='food-shop'?'foodShop':kind==='food-item'?'foodItem':kind==='shop-product'?'shopProduct':kind==='wishlist'?'wishlist':kind==='gift-plan'?'giftPlan':kind==='new-room'?'foodRoom':kind==='wish-item'?'wishlist':kind,...v};
if(kind==='food-shop'||kind==='food-item'||kind==='shop-product'){for(const k of ['fee','price','stock'])if(v[k]!==undefined)data[k]=Number(v[k])||0;if(kind==='food-shop'){data.open=true;data.rating=v.rating||'4.8'}if(kind==='food-item')data.active=true;if(kind==='shop-product')data.active=true;await put(data);toast(oid?'已保存修改':'已新增');closeModal();render();return}
if(kind==='new-room'){const ps=people(),ids=fd.getAll('personIds').map(String);const picked=ps.filter(p=>ids.includes(String(p.id)));data.kind='foodRoom';data.peopleIds=picked.map(p=>String(p.id));data.peopleNames=picked.map(p=>p.name);data.candidates=[];data.status='征集中';data.createdAt=new Date().toLocaleString();await put(data);toast('一起点餐房间已创建');closeModal();render();return}
if(kind==='wishlist'){data.kind='wishlist';data.items=oid?((await all('wishlist')).find(x=>x.id===oid)?.items||[]):[];data.budget=Number(v.budget)||0;await put(data);toast(oid?'愿望清单已更新':'愿望清单已创建');closeModal();render();return}
if(kind==='wish-item'){const w=(await all('wishlist')).find(x=>x.id===oid);if(w){w.items=w.items||[];w.items.push({name:v.itemName,price:Number(v.itemPrice)||0});await put(w)}toast('已添加愿望');closeModal();render();return}
if(kind==='gift-plan'){const ps=people(),p=ps.find(p=>String(p.id)===String(v.personId));data.kind='giftPlan';data.personName=p?.name||'';data.status=v.status||'准备中';data.budget=Number(v.budget)||0;data.candidates=v.candidateName?[{name:v.candidateName,price:Number(v.candidatePrice)||0}]:[];await put(data);toast(oid?'礼物计划已更新':'礼物计划已创建');closeModal();render();return}
}catch(err){console.error(err);toast('保存失败：浏览器可能没有可用空间，请稍后重试；已有资料未主动删除。')}}
function handleChange(e){}
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#lr-life-app')?.classList.contains('open')){if($('#life-modal')?.classList.contains('show'))closeModal();else close()}});
async function exportData(){const kinds=['foodShop','foodItem','foodCart','foodOrder','foodRoom','savedAddress','shopProduct','shopCart','shopOrder','wishlist','giftPlan'];const data={format:'LOVE_RECORD_LIFE_APPS',version:1,exportedAt:new Date().toISOString(),records:{}};for(const k of kinds)data.records[k]=await all(k);const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='love-record-life-apps-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);toast('已导出新应用数据备份')}
document.addEventListener('click',e=>{const a=e.target.closest('[data-launch-life]');if(a){e.preventDefault();open(a.dataset.launchLife)}},true);
window.LoveRecordLifeApps={open,close,exportData};
injectStyle();
})();
