/* LOVE RECORD MUSIC V2 · local library + online search + global draggable player */
(()=>{'use strict';
const DB='love-record-music-v1',STORE='tracks',META='meta';
const SOURCES=['netease','tencent','kugou','kuwo'];
const MUSIC_API='https://music-api.gdstudio.xyz/api.php';
let db,audio,tracks=[],current=null,queue=[],history=[],objectUrl=null,onlineResults=[],dragTimer=null,dragging=false,dragStart=null,ignoreClick=false;
const $=id=>document.getElementById(id);
function req(r){return new Promise((res,rej)=>{r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE,{keyPath:'id'});if(!d.objectStoreNames.contains(META))d.createObjectStore(META,{keyPath:'key'})};r.onsuccess=()=>{db=r.result;res()};r.onerror=()=>rej(r.error)})}
async function all(){tracks=await req(db.transaction(STORE).objectStore(STORE).getAll());tracks.sort((a,b)=>b.added-a.added);renderLocal()}
async function put(t){await req(db.transaction(STORE,'readwrite').objectStore(STORE).put(t))}
async function del(id){await req(db.transaction(STORE,'readwrite').objectStore(STORE).delete(id));if(current?.kind==='local'&&current.id===id){audio.pause();audio.removeAttribute('src');current=null;saveState()}await all()}
async function saveState(){try{await req(db.transaction(META,'readwrite').objectStore(META).put({key:'player',current:current?serialTrack(current):null,queue:queue.map(serialTrack)}))}catch{}}
function serialTrack(t){return {id:t.id,title:t.title||'',artist:t.artist||'',source:t.source||'',kind:t.kind||'local',album:t.album||'',url:t.url||''}}
async function loadState(){const s=await req(db.transaction(META).objectStore(META).get('player'));if(s){queue=Array.isArray(s.queue)?s.queue:[];return s.current||null}return null}
function fmt(n){if(!Number.isFinite(n))return '0:00';return Math.floor(n/60)+':'+String(Math.floor(n%60)).padStart(2,'0')}
function toast(s){const el=$('musicToast');if(!el)return;el.textContent=s;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2600)}
function updateLabels(t){$('musicNowTitle').textContent=t?.title||'还没有播放歌曲';$('musicNowArtist').textContent=t?(t.artist||t.source||'音乐'):'从音乐库或在线搜索选择一首歌';$('musicMiniTitle').textContent=t?.title||'—';$('musicMiniArtist').textContent=t?(t.artist||t.source||'音乐'):'—';$('musicMini').hidden=!t}
function setButtons(){const playing=!audio.paused;$('musicPlay').textContent=playing?'Ⅱ':'▶';$('musicMiniPlay').textContent=playing?'Ⅱ':'▶'}
function renderLocal(){const q=($('musicSearch')?.value||'').trim().toLowerCase(),list=$('musicTrackList');if(!list)return;const arr=tracks.filter(t=>(t.title+' '+(t.artist||'')).toLowerCase().includes(q));$('musicLibraryCount').textContent=tracks.length+' TRACKS';list.innerHTML='';if(!arr.length){list.innerHTML='<div class="music-empty">'+(tracks.length?'没有找到相关歌曲。':'这里还没有歌曲。点击「添加音乐」上传你的第一首歌吧。')+'</div>';return}arr.forEach(t=>{const row=document.createElement('div');row.className='music-track';const play=document.createElement('button');play.className='music-track-play';play.type='button';play.textContent=current?.kind==='local'&&current.id===t.id&&!audio.paused?'Ⅱ':'▶';play.onclick=()=>current?.kind==='local'&&current.id===t.id?toggle():playTrack({...t,kind:'local'});const meta=document.createElement('div');meta.className='music-track-meta';const name=document.createElement('strong');name.textContent=t.title;const artist=document.createElement('span');artist.textContent=t.artist||'本地音乐';meta.append(name,artist);const remove=document.createElement('button');remove.className='music-track-delete';remove.type='button';remove.textContent='⋯';remove.title='删除歌曲';remove.onclick=()=>{if(confirm('从音乐库删除「'+t.title+'」？'))del(t.id)};row.append(play,meta,remove);list.append(row)})}
function normalizeList(data,source){let a=Array.isArray(data)?data:(data?.data?.list||data?.data?.songs||data?.data?.result||data?.list||data?.songs||data?.result||data?.data||[]);if(!Array.isArray(a)&&a&&typeof a==='object')a=Object.values(a);return (Array.isArray(a)?a:[]).map((x,i)=>({id:String(x.id??x.song_id??x.songmid??x.mid??x.hash??x.rid??i),title:String(x.name??x.title??x.songname??x.songName??x.SongName??'未知歌曲'),artist:String(x.artist??x.singer??x.author??x.artists?.map?.(v=>v.name).join(' / ')??x.SingerName??''),album:String(x.album??x.album_name??x.AlbumName??''),source:x.source||source,url:x.url||x.music_url||x.play_url||'',cover:x.pic||x.cover||x.pic_url||'',kind:'online'})).filter(x=>x.title!=='未知歌曲')}
async function apiJson(url){const r=await fetch(url,{method:'GET',mode:'cors',headers:{'Accept':'application/json'}});if(!r.ok)throw new Error('HTTP '+r.status);const text=await r.text();try{return JSON.parse(text)}catch{if(/^https?:\/\//i.test(text.trim()))return text.trim();throw new Error('音乐服务返回了无法识别的数据')}}
async function searchOnline(){const input=$('musicOnlineSearch'),keyword=input.value.trim();if(!keyword){toast('先输入歌名或歌手');return}const box=$('musicOnlineResults'),list=$('musicOnlineList'),btn=$('musicOnlineGo');box.hidden=false;list.innerHTML='<div class="music-empty">正在搜索音乐资源……</div>';$('musicOnlineCount').textContent='SEARCHING';btn.disabled=true;const selected=$('musicOnlineSource').value;const sources=selected==='all'?SOURCES:[selected];try{const batches=await Promise.all(sources.map(async source=>{const u=new URL(MUSIC_API);u.searchParams.set('types','search');u.searchParams.set('source',source);u.searchParams.set('name',keyword);u.searchParams.set('count','20');u.searchParams.set('pages','1');try{return normalizeList(await apiJson(u.toString()),source)}catch(e){return []}}));onlineResults=batches.flat();const seen=new Set();onlineResults=onlineResults.filter(t=>{const k=t.source+':'+t.id;if(seen.has(k))return false;seen.add(k);return true});renderOnline();if(!onlineResults.length)list.innerHTML='<div class="music-empty">没有取得搜索结果。可能是音乐服务暂时不可用，或浏览器跨域限制了请求。<br>可以稍后重试，或切换搜索来源。</div>'}catch(e){list.innerHTML='<div class="music-empty">搜索失败：'+escapeHtml(e.message)+'</div>'}finally{btn.disabled=false}}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderOnline(){const list=$('musicOnlineList');list.innerHTML='';$('musicOnlineCount').textContent=onlineResults.length+' SONGS';if(!onlineResults.length)return;onlineResults.forEach((t,i)=>{const row=document.createElement('div');row.className='music-result-row';const cb=document.createElement('input');cb.type='checkbox';cb.className='music-result-check';cb.dataset.index=i;const meta=document.createElement('div');meta.className='music-result-meta';const title=document.createElement('strong');title.textContent=t.title;const sub=document.createElement('span');sub.textContent=[t.artist,t.album,t.source].filter(Boolean).join(' · ');meta.append(title,sub);const play=document.createElement('button');play.className='music-result-play';play.type='button';play.textContent='▶';play.title='试听';play.onclick=()=>playTrack(t);row.append(cb,meta,play);list.append(row)})}
async function resolveOnline(t){if(t.url)return t.url;const u=new URL(MUSIC_API);u.searchParams.set('types','url');u.searchParams.set('source',t.source);u.searchParams.set('id',t.id);u.searchParams.set('br','320');const d=await apiJson(u.toString());const url=d?.url||d?.data?.url||d?.data?.play_url||d?.music_url||d?.data?.music_url||(typeof d==='string'?d:'');if(!url||!/^https?:\/\//i.test(url))throw new Error('这个版本暂时没有可播放音源');return url}
async function playTrack(t){try{if(objectUrl){URL.revokeObjectURL(objectUrl);objectUrl=null}current=t;if(t.kind==='local'){objectUrl=URL.createObjectURL(t.blob);audio.src=objectUrl}else{toast('正在获取播放地址……');audio.src=await resolveOnline(t)}audio.load();updateLabels(t);await saveState();await audio.play();setButtons();renderLocal()}catch(e){audio.pause();toast('暂时无法播放：'+e.message);setButtons()}}
function toggle(){if(!current){if(tracks[0])playTrack({...tracks[0],kind:'local'});else if(queue.length)next();else toast('请先添加或搜索歌曲');return}if(audio.paused){if(!audio.src||current.kind==='online'&&!audio.src)playTrack(current);else audio.play().then(setButtons).catch(()=>toast('浏览器阻止播放，请再点一次'))}else audio.pause()}
function addFiles(files){return (async()=>{let count=0;for(const f of [...files]){if(!f.type.startsWith('audio/'))continue;const id='track-'+Date.now()+'-'+Math.random().toString(36).slice(2,8);await put({id,title:f.name.replace(/\.[^.]+$/,''),artist:'',blob:f,mime:f.type,size:f.size,added:Date.now(),duration:0});count++}await all();toast('已添加 '+count+' 首本地歌曲 ♡')})()}
function addSelected(){const ids=[...document.querySelectorAll('.music-result-check:checked')].map(x=>Number(x.dataset.index));if(!ids.length){toast('请先勾选歌曲');return}const chosen=ids.map(i=>onlineResults[i]).filter(Boolean);queue.push(...chosen);saveState();toast('已加入 '+chosen.length+' 首歌曲 ♡');if(!current)playTrack(queue.shift());}
function next(){if(queue.length){let t=queue.shift();if(t.kind==='local'){const found=tracks.find(x=>x.id===t.id);if(found)t={...found,kind:'local'}}history.push(current);saveState();if(t?.blob||t?.kind==='online')playTrack(t);else next();return}if(current?.kind==='local'&&tracks.length){const i=tracks.findIndex(t=>t.id===current.id);playTrack({...tracks[(i+1)%tracks.length],kind:'local'});return}audio.pause();toast('播放队列已结束')}
function prev(){if(audio.currentTime>3){audio.currentTime=0;return}const t=history.pop();if(t)playTrack(t);else if(current?.kind==='local'&&tracks.length){const i=tracks.findIndex(x=>x.id===current.id);playTrack({...tracks[(i-1+tracks.length)%tracks.length],kind:'local'})}}
function initDrag(){const el=$('musicMini');if(!el)return;try{const saved=JSON.parse(localStorage.getItem('lrMusicMiniPosition')||'null');if(saved&&Number.isFinite(saved.x)&&Number.isFinite(saved.y)){el.style.left=saved.x+'px';el.style.top=saved.y+'px';el.style.right='auto';el.style.bottom='auto'}}catch{}
el.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;dragging=false;ignoreClick=false;dragStart={x:e.clientX,y:e.clientY,ox:el.getBoundingClientRect().left,oy:el.getBoundingClientRect().top};clearTimeout(dragTimer);dragTimer=setTimeout(()=>{dragging=true;el.classList.add('dragging');try{el.setPointerCapture(e.pointerId)}catch{}},380)});
el.addEventListener('pointermove',e=>{if(!dragStart||!dragging)return;const r=el.getBoundingClientRect(),x=Math.max(4,Math.min(innerWidth-r.width-4,dragStart.ox+e.clientX-dragStart.x)),y=Math.max(8,Math.min(innerHeight-r.height-8,dragStart.oy+e.clientY-dragStart.y));el.style.left=x+'px';el.style.top=y+'px';el.style.right='auto';el.style.bottom='auto';ignoreClick=true});
const end=()=>{clearTimeout(dragTimer);if(dragging){const r=el.getBoundingClientRect();localStorage.setItem('lrMusicMiniPosition',JSON.stringify({x:r.left,y:r.top}));setTimeout(()=>ignoreClick=false,80)}dragging=false;dragStart=null;el.classList.remove('dragging')};el.addEventListener('pointerup',end);el.addEventListener('pointercancel',end)}
function init(){audio=$('lrGlobalAudio');if(!audio)return;audio.addEventListener('play',()=>{setButtons();renderLocal()});audio.addEventListener('pause',()=>{setButtons();renderLocal()});audio.addEventListener('timeupdate',()=>{const p=audio.duration?audio.currentTime/audio.duration*100:0;$('musicProgress').value=p;$('musicCurrentTime').textContent=fmt(audio.currentTime);$('musicDuration').textContent=fmt(audio.duration);$('musicMiniProgress').style.width=p+'%'});audio.addEventListener('ended',next);
$('musicUpload').onclick=()=>$('musicFiles').click();$('musicFiles').onchange=e=>{addFiles(e.target.files).catch(()=>toast('歌曲保存失败，请检查浏览器储存空间'));e.target.value=''};$('musicSearch').oninput=renderLocal;$('musicPlay').onclick=toggle;$('musicMiniPlay').onclick=toggle;$('musicPrev').onclick=prev;$('musicNext').onclick=next;$('musicProgress').oninput=()=>{if(audio.duration)audio.currentTime=audio.duration*Number($('musicProgress').value)/100};$('musicVolume').oninput=()=>audio.volume=Number($('musicVolume').value);$('musicShuffle').onclick=()=>{queue=tracks.map(t=>({id:t.id,title:t.title,artist:t.artist,kind:'local'})).sort(()=>Math.random()-.5);saveState();toast('已将本地歌曲加入随机队列')};$('musicRepeat').onclick=()=>{audio.loop=!audio.loop;$('musicRepeat').classList.toggle('active',audio.loop)};$('musicClearSearch').onclick=()=>{$('musicSearch').value='';renderLocal()};
$('musicOnlineGo').onclick=searchOnline;$('musicOnlineSearch').addEventListener('keydown',e=>{if(e.key==='Enter')searchOnline()});$('musicAddSelected').onclick=addSelected;$('musicSelectAll').onchange=e=>document.querySelectorAll('.music-result-check').forEach(x=>x.checked=e.target.checked);
initDrag();openDB().then(async()=>{const saved=await loadState();await all();if(saved){if(saved.kind==='local'){const t=tracks.find(x=>x.id===saved.id);if(t){current={...t,kind:'local'};objectUrl=URL.createObjectURL(t.blob);audio.src=objectUrl;updateLabels(current)}}else{current=saved;updateLabels(current);if(saved.url)audio.src=saved.url}}}).catch(()=>toast('音乐库初始化失败'))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();