/* LOVE RECORD MUSIC · local library player (online API adapter reserved) */
(()=>{'use strict';
const DB='love-record-music-v1',STORE='tracks',META='meta';let db,audio,tracks=[],currentId=null,queue=[],objectUrl=null;
const $=id=>document.getElementById(id);
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE,{keyPath:'id'});if(!d.objectStoreNames.contains(META))d.createObjectStore(META,{keyPath:'key'})};r.onsuccess=()=>{db=r.result;res()};r.onerror=()=>rej(r.error)})}
function req(r){return new Promise((res,rej)=>{r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function all(){tracks=await req(db.transaction(STORE).objectStore(STORE).getAll());tracks.sort((a,b)=>b.added-a.added);render()}
async function put(t){await req(db.transaction(STORE,'readwrite').objectStore(STORE).put(t))}
async function del(id){await req(db.transaction(STORE,'readwrite').objectStore(STORE).delete(id));if(currentId===id){audio.pause();audio.removeAttribute('src');currentId=null;await saveState()}await all()}
async function saveState(){await req(db.transaction(META,'readwrite').objectStore(META).put({key:'player',currentId,queue}))}
async function loadState(){const s=await req(db.transaction(META).objectStore(META).get('player'));if(s){currentId=s.currentId||null;queue=Array.isArray(s.queue)?s.queue:[]}}
function fmt(n){if(!Number.isFinite(n))return '0:00';return Math.floor(n/60)+':'+String(Math.floor(n%60)).padStart(2,'0')}
function active(){return tracks.find(x=>x.id===currentId)}
function setTrack(t,autoplay=true){if(!t)return;currentId=t.id;if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=URL.createObjectURL(t.blob);audio.src=objectUrl;audio.load();$('musicNowTitle').textContent=t.title;$('musicNowArtist').textContent=t.artist||'Unknown artist';$('musicMiniTitle').textContent=t.title;$('musicMiniArtist').textContent=t.artist||'Unknown artist';$('musicMini').hidden=false;saveState();if(autoplay)audio.play().catch(()=>toast('浏览器阻止了自动播放，请再点一次播放')) ;render()}
function render(){const q=($('musicSearch')?.value||'').trim().toLowerCase();const list=$('musicTrackList');if(!list)return;const arr=tracks.filter(t=>(t.title+' '+(t.artist||'')).toLowerCase().includes(q));$('musicLibraryCount').textContent=tracks.length+' TRACKS';list.innerHTML='';if(!arr.length){list.innerHTML='<div class="music-empty">'+(tracks.length?'没有找到相关歌曲。':'这里还没有歌曲。点击「添加音乐」上传你的第一首歌吧。')+'</div>';return}arr.forEach(t=>{const row=document.createElement('div');row.className='music-track';const play=document.createElement('button');play.className='music-track-play';play.type='button';play.textContent=t.id===currentId&& !audio.paused?'Ⅱ':'▶';play.onclick=()=>{if(currentId===t.id){audio.paused?audio.play():audio.pause()}else setTrack(t)};const meta=document.createElement('div');meta.className='music-track-meta';const name=document.createElement('strong');name.textContent=t.title;const artist=document.createElement('span');artist.textContent=t.artist||'本地音乐';meta.append(name,artist);const duration=document.createElement('small');duration.textContent=t.duration?fmt(t.duration):'';const remove=document.createElement('button');remove.className='music-track-delete';remove.type='button';remove.textContent='⋯';remove.title='删除歌曲';remove.onclick=()=>{if(confirm('从音乐库删除「'+t.title+'」？'))del(t.id)};row.append(play,meta,duration,remove);list.append(row)})}
async function addFiles(files){for(const f of [...files]){if(!f.type.startsWith('audio/'))continue;const id='track-'+Date.now()+'-'+Math.random().toString(36).slice(2,8);const title=f.name.replace(/\.[^.]+$/,'');await put({id,title,artist:'',blob:f,mime:f.type,size:f.size,added:Date.now(),duration:0})}await all();toast('已添加 '+files.length+' 首歌曲 ♡')}
function toast(s){const el=$('musicToast');if(!el)return;el.textContent=s;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function init(){audio=$('lrGlobalAudio');if(!audio)return;audio.addEventListener('play',()=>{$('musicPlay').textContent='Ⅱ';$('musicMiniPlay').textContent='Ⅱ';render()});audio.addEventListener('pause',()=>{$('musicPlay').textContent='▶';$('musicMiniPlay').textContent='▶';render()});audio.addEventListener('timeupdate',()=>{const p=audio.duration?audio.currentTime/audio.duration*100:0;$('musicProgress').value=p;$('musicCurrentTime').textContent=fmt(audio.currentTime);$('musicDuration').textContent=fmt(audio.duration);$('musicMiniProgress').style.width=p+'%'});audio.addEventListener('ended',next);
$('musicUpload').onclick=()=>$('musicFiles').click();$('musicFiles').onchange=e=>{addFiles(e.target.files).catch(()=>toast('歌曲保存失败，请检查浏览器储存空间'));e.target.value=''};$('musicSearch').oninput=render;$('musicPlay').onclick=toggle;$('musicMiniPlay').onclick=toggle;$('musicPrev').onclick=prev;$('musicNext').onclick=next;$('musicProgress').oninput=()=>{if(audio.duration)audio.currentTime=audio.duration*Number($('musicProgress').value)/100};$('musicVolume').oninput=()=>audio.volume=Number($('musicVolume').value);$('musicShuffle').onclick=()=>{queue=tracks.map(t=>t.id).sort(()=>Math.random()-.5);saveState();toast('已开启随机播放队列')};$('musicRepeat').onclick=()=>{audio.loop=!audio.loop;$('musicRepeat').classList.toggle('active',audio.loop)};$('musicClearSearch').onclick=()=>{$('musicSearch').value='';render()};
openDB().then(async()=>{await loadState();await all();const t=active();if(t){objectUrl=URL.createObjectURL(t.blob);audio.src=objectUrl;$('musicNowTitle').textContent=t.title;$('musicNowArtist').textContent=t.artist||'Unknown artist';$('musicMiniTitle').textContent=t.title;$('musicMiniArtist').textContent=t.artist||'Unknown artist';$('musicMini').hidden=false}}).catch(()=>toast('音乐库初始化失败'));
}
function toggle(){if(!audio.src){const t=tracks[0];if(t)setTrack(t);else toast('请先添加一首音乐');return}audio.paused?audio.play().catch(()=>toast('请再点一次播放')):audio.pause()}
function next(){if(queue.length){const id=queue.shift();saveState();const t=tracks.find(x=>x.id===id);if(t){setTrack(t);return}}const i=tracks.findIndex(t=>t.id===currentId);setTrack(tracks[(i+1+tracks.length)%tracks.length])}
function prev(){if(audio.currentTime>3){audio.currentTime=0;return}const i=tracks.findIndex(t=>t.id===currentId);setTrack(tracks[(i-1+tracks.length)%tracks.length])}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
